### ISSUE TITLE
Option to see character descriptions in the Grimoire

### ISSUE THREAD

**Issue by ivanhoe1403** [Skateside/pocket-grimoire#114]
Would it be possible to include the option to have the character text included on the tokens directly?
This way the storyteller just needs to glance at the Grimoire in case of doubt (for example, some characters have to pick a different player each night, but some can keep picking the same one over and over...).
Of course, they can just click on the token and the text pops up, but if this extra action isn't done, it can cause mistakes.

**Comment by ivanhoe1403** [comment]
On the other hand, this info can be seen in the night order, so please ignore...

**Comment by Skateside** [comment]
I don't know if there epild be enough space, but since the information is already in the night order, I'll close this ticket
