### ISSUE TITLE
Minstrel doesn't appear in the night order

### ISSUE THREAD

**Issue by ivanhoe1403** [Skateside/pocket-grimoire#115]
Could be possibly related to this: https://github.com/Skateside/pocket-grimoire/issues/74

Would it be possible to add Minstrel to the night order?
Thank you.

**Comment by Skateside** [comment]
The Minstrel isn't supposed to appear in the night order. Everyone becomes drunk when the Minstrel is executed (assuming they're sober and healthy) so there's nothing that actually happens overnight

**Comment by ivanhoe1403** [comment]
@Skateside 
It's possible that it changed over time, but I see Minstrel included in the BMR Night Order (see here for example: http://bignose.whitetree.org/projects/botc/diy/reference/bad-moon-rising.pdf)

It's honestly the only role from the 3 base scripts that's not included in the Pocket Grimoire night order and it would be really nice to have it there, just to ensure the storyteller won't forget to check and make everyone drunk when a Minion was executed (I know I'll forget for sure...).

**Comment by Skateside** [comment]
I think that's an older version. The official sheet doesn't put the Minstrel on there 

![Uploading 17171410356185784529975110916847.jpg…]()

**Comment by ivanhoe1403** [comment]
I see.
If you're trying to replicate the physical version as close as possible, then I understand.
I guess I'll use the storyteller notes to put down a reminder...
Thanks for your work, the app is really great.

**Comment by Skateside** [comment]
In a future version of the PG you'll be able to upload a custom night order with the script and that would allow you to include the Minstrel. Right now, I think the PG should match a physical copy as much as possible

**Comment by ivanhoe1403** [comment]
That sounds great.
Any idea when would you like to have the future version available?

**Comment by Skateside** [comment]
Its at least a few months away 😅
I don't get an awful lot of time these days so it's not always easy to work on the updated version. Keep an eye on the discord channel, I'll post updates there (when I have any)

**Comment by ivanhoe1403** [comment]
Sounds good :D
