### ISSUE TITLE
trouble brewing: error role order overnight

### ISSUE THREAD

**Issue by japarrado** [Skateside/pocket-grimoire#119]
I have detected two errors in the order of roles during the night (first night and others night): spy and undertaker 

Can someone review it?

Thank you

ps: the discord group invitation has expired

**Comment by Skateside** [comment]
Hi @japarrado 

I tend to get the roles from the official script tool and the order seems to be consistent (unless I've missed something)
https://script.bloodontheclocktower.com/data/nightsheet.json

Thanks for letting me know about the Discord link - I've updated it

Skateside

**Comment by Skateside** [comment]
Hi @japarrado 

I'm afraid that I can't fix this one. I get the night order from the nightsheet that I linked in my previous comment, that has the spy after the Imp. Unless I re-write the Pocket Grimoire, I can't pass in a custom night order for a script, so I won't be able to solve this one.

Sorry
Skateside

**Comment by Skateside** [comment]
Hi @japarrado 

I've taken another look into this issue and managed to solve it. You should be able to have custom night orders (including Trouble Brewing automatically showing the Spy before the Imp) now.

Cheers
Skateside
