### ISSUE TITLE
New Korean language update

### ISSUE THREAD

**Issue by kabalier** [Skateside/pocket-grimoire#122]
the necessary language files have been updated.
(In the Jinx file, only the proper nouns were abbreviated, but I think it will be enough)

plz update korean language. thk!
*I am unable to connect to the Discord server.

**Comment by Skateside** [comment]
Hi @kabalier 

Thanks for updating the Community translations and the jinxes. Would you be able to translate the Pocket Grimoire text file as well, please? If that's done, I can add Korean to the Pocket Grimoire
https://docs.google.com/spreadsheets/d/1YjI3LcLnLbuONbjbniZTZa1BIT8MKBb8TuIprtmkjAw/edit?gid=0#gid=0

Thanks
Skateside

**Comment by kabalier** [comment]
It's already been translated!
 This meant that only the words that needed to jinxes were translated, and everything else was translated

**Comment by kabalier** [comment]
ah! that sheet name is "kr_KR",

**Comment by Skateside** [comment]
Hi @kabalier 

Thanks for that
Would you be able to translate the jinxes, please? I can see that the character names have been translated, but the rest of the text hasn't. I can run that through Google Translate, but it might not be as accurate.

Thanks
Skateside

**Comment by kabalier** [comment]
Done!

**Comment by Skateside** [comment]
Thanks @kabalier - the Pocket Grimoire now has Korean

**Comment by kabalier** [comment]
could change the word "한국인“ to ”한국어“?

the meaning of first word is "korea people"

**Comment by Skateside** [comment]
Sorry - that's been updated

**Comment by kabalier** [comment]
Thanks!

What if I want to go through some typos and mistranslations?

**Comment by Skateside** [comment]
@kabalier update the translation documents mentioned in the README file and let me know thatbyouve made changes. 

If you could let me know what you've changed then it would make it easier for me to update the app, but it's not essential
