### ISSUE TITLE
Can not browse custom script using ipad

### ISSUE THREAD

**Issue by seeroffish** [Skateside/pocket-grimoire#126]
when using ipad I choose "select edition" -> "Upload a custom script" -> "Browse" and there's no response

**Comment by Skateside** [comment]
Hi @seeroffish 

I don't have an ipad, so I might have difficulty debugging this one, but is the issue still happening? I've made a few changes since you raised this issue and it might have been resolved as a result.

Cheers
Skateside

**Comment by Skateside** [comment]
I've heard nothing for over a month - closing this issue
