### ISSUE TITLE
[BUG] Jinxes do not appear as "in-play" when replace-character tokens are used.

### ISSUE THREAD

**Issue by GrayPockets** [Skateside/pocket-grimoire#128]
When a character such as the Marionette, Drunk, or Apprentice has a jinx, the jinxes do not appear "in-play" unless the Token is used, instead of the reminder token.

**Steps to Reproduce**

1. Navigate to https://www.pocketgrimoire.co.uk/en_GB/
3. Clear your cache (Click Clear Cache > Clear Cache)
4. Select the custom edition: (Select edition > Custom Script > Paste from clipboard: [{"id":"_meta","author":"GrayPockets","name":"Swapathon"},"balloonist","marionette"]
6. Click "Add token" and select the "Balloonist"
7. Click "Add reminder" and select "Is the Marionette"

**Expected Outcome** The Balloonist/Marionette jinx should appear as in-play
**Actual Outcome** No jinxes appear as in-play

![image](https://github.com/user-attachments/assets/8c618901-b689-4c24-a634-462f63417ed4)
![image](https://github.com/user-attachments/assets/3e641dd6-5b01-4823-a7c6-22ab3843761c)
![image](https://github.com/user-attachments/assets/82d26e70-f92a-4ced-8e5f-d00af33984f2)

**Comment by Skateside** [comment]
Hi @GrayPockets 

This should be sorted now.

Cheers
Skateside
