### ISSUE TITLE
[BUG] Some urls do not work when calling custom scripts

### ISSUE THREAD

**Issue by GrayPockets** [Skateside/pocket-grimoire#129]
Some scripts do not load when using a URL.
These scripts load when uploaded directly or pasted.
I also tried it without the space (https://www.impeccabletiming.net/botc/DeliriumPromenade.json)

**Steps to Reproduce**

1. Navigate to https://www.pocketgrimoire.co.uk/en_GB/
2. Clear your cache (Click Clear Cache > Clear Cache)
3. Start selecting a custom edition: (Select edition > Custom Script )
4. In the "Enter a URL" box, type the following: "https://www.impeccabletiming.net/botc/Delirium%20Promenade.json"
5. Click "Select"

**Expected Outcome** The script should load
**Actual Outcome** An error message appears: "The script format has not been recognised."

![image](https://github.com/user-attachments/assets/86276f34-41bf-47cc-97a2-ecbfd6a6deef)

**Comment by Skateside** [comment]
Hi @GrayPockets 

This should be resolved now.

Cheers
Skateside

**Comment by GrayPockets** [comment]
Can confirm! Thanks!
