### ISSUE TITLE
Tokens can't be moved around

### ISSUE THREAD

**Issue by ivanhoe1403** [Skateside/pocket-grimoire#137]
Hello @Skateside 
Never had this bug in the past, but just noticed this (on Win & Mac)...

When I try to move a token (player token, reminder token...) it sticks to the cursor once I release it, so in essence I can't place it anywhere.
Everything looks good until you try to move them around, makes it impossible to use the grim...

Can you please have a look?
Thank you.

**Comment by Skateside** [comment]
This is a weird one because it only happens on the uploaded code, it doesn't happen locally. I'll try to take a look at it this weekend

**Comment by Skateside** [comment]
@ivanhoe1403 This should be sorted now
