### ISSUE TITLE
Xaan not on script

### ISSUE THREAD

**Issue by lemonlavendermoon** [Skateside/pocket-grimoire#140]
I'm trying to add a script json created in the official Blood on the Clocktower script making tool, and when I upload the json to Pocket Grimoire it's not adding the Xaan experimental character. Is there a way to include it? Thank you so much!

**Comment by Skateside** [comment]
Hi @lemonlavendermoon 

This has been resolved now. Sorry that it took so long.

Cheers
Skateside
