### ISSUE TITLE
Add Polish translation

### ISSUE THREAD

**Issue by fuine** [Skateside/pocket-grimoire#142]
I've added Polish translation to all appropriate files:

* [The Community BotC Translations](https://docs.google.com/spreadsheets/d/1aAJdqSTafHnw01w-WZ94UPx1Me70Kz-EG1NFfBht2tA/edit#gid=923580658) under the sheet `pl_PL (fuine)`
* [The Jinxes](https://docs.google.com/spreadsheets/d/1EJQzuQNlzTvNzAOJEIldu0ILKNU3UhsgFr-TZnhxpVM/edit#gid=1649450121) under the sheet `pl_PL`, although these entries are in accordance with data from [the official script tool jinxes data](https://script.bloodontheclocktower.com/data/jinx.json) and it has less entries than the english sheet - let me know if this is a potential problem for you. I've opened #141 to highlight the mismatch.
* [The Pocket Grimoire](https://docs.google.com/spreadsheets/d/1YjI3LcLnLbuONbjbniZTZa1BIT8MKBb8TuIprtmkjAw/edit#gid=19211044) under the sheet `pl_PL`

Can you add the translation to the app?

**Comment by Skateside** [comment]
Done :)
