### ISSUE TITLE
Add text boxes for storyteller's convenience

### ISSUE THREAD

**Issue by Skateside** [Skateside/pocket-grimoire#38]
This is based on #35

**Comment by Skateside** [comment]
I don't see how this is useful. I feel like the user's phone probably has some kind of notepad app which would do the same thing

**Comment by zenador** [comment]
That's what I'm doing currently as a temporary workaround, but I hate having to switch between apps so I added this. Would much prefer the game to be self-contained. Once, when I was using the notepad app my phone decided to kill the browser. And in cases when you need to pass the digital grimoire around to players or to co-storytellers, it's also nice to be able to lock your phone to one app so they can't switch to another.

**Comment by Skateside** [comment]
I'll leave the ticket open just in-case someone else says that they need this functionality, but it doesn't seem like something common to me. I can't think why a storyteller would need to pass complex information to a player (might not be necessary anymore now that #37 is done) or have a two-way conversation overnight. I also can't really think why one storyteller couldn't just take the other one aside and explain anything they need to

**Comment by zenador** [comment]
Sometimes you need to clarify something at night. But it's up to you, thanks for working on this anyway!

**Comment by Skateside** [comment]
It's been a few months, no-one else has stepped forward saying that this feature would be useful. I'm going to close this issue

**Comment by Boardbender** [comment]
I would also find this feature very useful, it is included as "custom note" status token on clocktower.online and i use it often.  In most cases i run the pocket grimoire on a tablet with a bigger screen size and it works very well. However, not being able to make any notes is a bit inconvenient because you have to switch to another program or pen and paper.

**Comment by zenador** [comment]
This issue here is about a simple text box for jotting down text with no max length, if you want a status token with a custom note, https://github.com/Skateside/pocket-grimoire/issues/85 might be better

**Comment by Skateside** [comment]
Hi @zenador and @Boardbender 

I've added a simple text box so that notes can be added. There's a button that will clear the notes (and it'll give you a warning before you do) and pressing the "Clear Grimoire" button won't clear those notes, allowing the notes to be remembered from game to game, just in-case.

Might be worth stressing that if you clear the cache, the notes will disappear.

Cheers
Skateside
