### ISSUE TITLE
Add button to character choice dialog to open all tokens at once and add them to the grimoire

### ISSUE THREAD

**Issue by Skateside** [Skateside/pocket-grimoire#39]
This is based on #35

**Comment by Skateside** [comment]
I don't really know what this is or how it's convenient.

**Comment by zenador** [comment]
This is very convenient for those who play with a mix of physical and digital grimoires. The people I play with prefer the experience of drawing from a bag over tapping buttons on a screen, but as a storyteller I prefer the digital grimoire. Right now I use this app to choose the characters for the initial setup, prepare the corresponding physical tokens in a bag for the players, and then open the digital tokens one by one by myself, which is a pain in bigger games.

**Comment by Skateside** [comment]
This is sounding like a very niche issue. If players can draw tokens out of a bag then it sounds like you already have a physical copy. Surely that's the better experience all-round?

**Comment by zenador** [comment]
If it were I wouldn't bother with this, but it's fine if you would rather not add this button for everyone.

**Comment by Skateside** [comment]
@zenador 

OK ... this one's been bouncing around the ol' noodle for a couple of days ... am I right in thinking that you basically need a way of adding a lot of characters to the grimoire at once because you may be looking to copy the setup of another grimoire, be it the physical copy and you want the digital abilities, or you're co-storytelling and want your own version?

If that's the case, I don't think I'd want that in the character selection screen, but there's already a screen that shows all the tokens in the script - the "Add token" button in the Grimoire section. If I could set it up so that multiple of them could be added, would that basically be something like the functionality you're imagining?

**Comment by zenador** [comment]
> to copy the setup of another grimoire, be it the physical copy and you want the digital abilities, or you're co-storytelling and want your own version

Yes, that's right.

> If I could set it up so that multiple of them could be added, would that basically be something like the functionality you're imagining?

It would be halfway there, less convenient than the current button as I would have already selected the characters in the setup screen (it's great for ensuring you have the right counts of each type, or randomising) and would need to remember them and select them again, but better than nothing. Please don't worry about my use-cases if they are too niche though, I can just run a fork. But I think that what you suggested would be convenient for everyone in general even if they don't share this use-case.

If your main concern is that you don't want that button in the character selection screen though, I think moving it one screen earlier to the bottom of the character setup screen (below the 'Draw Characters' button) would work, to me that's just as good.

**Comment by Skateside** [comment]
OK, I've added the button to the screen before (Select Characters)

**Comment by zenador** [comment]
Awesome, thank you very much! This app makes storytelling much more efficient 😄
