### ISSUE TITLE
Make token size slider section collapsible

### ISSUE THREAD

**Issue by binhnefits** [Skateside/pocket-grimoire#41]
Sometimes when scrolling from the Grimore section down to Night Order section, the sliders can often get touched. It would be nice if that section can be collapsible for convenience.

**Comment by Skateside** [comment]
Hi @binhnefits 

Yeah, that makes some sense. I'll try to get that done over the Christmas break

**Comment by Skateside** [comment]
Hi @binhnefits 

I've created a collapsible section and moved the sliders into it.

**Comment by binhnefits** [comment]
Thank you looks great!
