### ISSUE TITLE
Optional input for names on "Draw Characters" phase

### ISSUE THREAD

**Issue by chepash** [Skateside/pocket-grimoire#44]
First of all, great app guys. Didn't expect that i could run the game just using my phone. But i was in new company of 13 people. Barely knew them.

And after dealing all roles i needed to sign names under all tokens, it took some time... long time. Always re-asking "what your name again? How to write it down?"

Would be great option, to have optional Input when people draw characters. And they could fill it by themself if they want. With this option I think your app would be even greater then my real version of the BotC game. Because name labels under tokens already super cool feature of your app.

**Comment by chepash** [comment]
![image](https://user-images.githubusercontent.com/100382249/217846794-f5bc76f9-3487-4ce8-a316-a7e143ebf311.png)

**Comment by Skateside** [comment]
I like it. Names for players was an after-thought so it's probably not very well integrated. I like your idea and I'll see what I can do about getting it in place

**Comment by Skateside** [comment]
Hey @chepash 

I've added that functionality. It remembers the names and suggests them next time, which should speed things up if you play more than one game in a night. The same functionality exists when you set the name by tapping on a token in the grimoire section.

I hope you like it

Cheers
