### ISSUE TITLE
Custom Script "invalid data" error

### ISSUE THREAD

**Issue by Kethuel** [Skateside/pocket-grimoire#46]
Attempting to load a custom script .json file gives an "invalid data" error if that script has a meta object (ie containing author name, script title, image, etc.). Many scripts on the https://botc-scripts.azurewebsites.net/ have this data so I reckon it'd be handy I didn't have to edit it out.

**Comment by Skateside** [comment]
@Kethuel I thought I'd already worked around that but it seems like it isn't working. Do you have an example script that you can share that throws the error? I'll take a look at it

**Comment by Kethuel** [comment]
Hiya,

Here's an example of a script that fails.

Regards,
Fletcher

**Comment by Skateside** [comment]
Hi @Kethuel 

I've managed to figure out what was causing this. You should be able to upload scripts again now.

Cheers
Skateside

**Comment by Kethuel** [comment]
Awesome! :)
