### ISSUE TITLE
Bug: Highlight random sometimes does not reset tokens properly

### ISSUE THREAD

**Issue by zenador** [Skateside/pocket-grimoire#53]
Very minor bug with simple fix.

How to reproduce:
1. Set the number of players to 8
2. Press 'highlight random'
3. Set the number of players to 7 (imagine someone suddenly decided to leave)
4. Press 'highlight random'

Observed behaviour:
There is still 1 outsider selected.

Expected behaviour:
No outsiders selected as there are none by default for the new player count.

**Comment by Skateside** [comment]
Confirmed, merged, and fixed - thanks, @zenador !
