### ISSUE TITLE
One-Click Token Change Option.

### ISSUE THREAD

**Issue by chepash** [Skateside/pocket-grimoire#63]
The more I play the game, the more I notice the use of the mechanic of permanently changing the player character to another character. For example, due to the abilities of Pit Hag and Bartender or Fang Gu, and some other custom characters.

Usually, algorithm is:
 - I have to create a new token
 - enter the player's name for it
 - to correctly place the token in the grimoire
 - the old token needs to be deleted so that it doesn't appear in the "night order".

I would like to have a simple option of "change token" in one click.

Something like this for a example:

![image](https://github.com/Skateside/pocket-grimoire/assets/100382249/d7739def-2afe-4c10-a2e5-f4e51a39438e)

 As a result, I have a new token with player name already signed, token placed in the same position as old one. And I panic less about the night dragging on for too long.

**Comment by Skateside** [comment]
I like it - I'll see what I can do

**Comment by Skateside** [comment]
Hey @chepash 

I've added that functionality. There's a new button called "Replace" that will swap out one token for another.

Cheers
Skateside
