### ISSUE TITLE
Multi-touching The Grimoire sometimes locks a component in drag mode

### ISSUE THREAD

**Issue by dconman** [Skateside/pocket-grimoire#66]
Sometimes when dragging a component in the Grim I will accidentally touch it with another finger. Often, this will lock that component into being dragged and I become unable to scroll the page or stop moving that component.

**Comment by Skateside** [comment]
I had a quick play around with my phone and I couldn't reproduce this one. I'll take a look at the code and see if I can spot anything obvious

**Comment by Skateside** [comment]
Thank you so much. I watched that video and immediately reproduced it on my phone. This gives me something I can look into. Thanks again

**Comment by Skateside** [comment]
@dconman I managed to figure out what was causing that issue and I sorted it out. You might need to refresh the Pocket Grimoire to see the fix, but that should prevent the issue happening again
