### ISSUE TITLE
Translation to Spain's spanish

### ISSUE THREAD

**Issue by Neturo47** [Skateside/pocket-grimoire#67]
Hi! Would it be possible to add a spanish translation apart from the argentinian one? I would really like to help translating it if you accept help! It's just that me and some other spanish friends want to play in our native language but some argentinian expressions are quite different to the Spanish we're used to, so having a "spanish spanish" translation would be great!

I already have a translation for all names and abilities in Trouble Brewing that I'm using with my group of friends, so if for some reason, as I said, you accept help from whoever offers it to you, I'd love to help!

Cheers!

**Comment by Skateside** [comment]
Yup, Spanish can be added. I just need Spanish added to the translation files listed here
https://github.com/Skateside/pocket-grimoire#translations-and-typos

It looks like the first one already has Spanish translations so we need the other two. As soon as that's done, I'll add Spanish to the Pocket Grimoire

**Comment by Skateside** [comment]
I'm going to close this issue since there's not much that I can do about it. If "spanish spanish" translations are added to the Pocket Grimoire file (https://docs.google.com/spreadsheets/d/1YjI3LcLnLbuONbjbniZTZa1BIT8MKBb8TuIprtmkjAw/edit?usp=sharing) then I'll get it added
