### ISSUE TITLE
Homebrew Jinxes

### ISSUE THREAD

**Issue by Skateside** [Skateside/pocket-grimoire#70]
They're currently not supported, but they should be.

Here's the syntax for a homebrew character that has a jinx

```json
{
    "id": "perfumer_the_bootleggers_anthology",
    "image": [
        "https://www.bloodstar.xyz/p/Elluna/The_Bootleggers_Anthology/perfumer_the_bootleggers_anthology.png"
    ],
    "reminders": [
        "Poisoned",
        "Betrayed"
    ],
    "name": "Perfumer",
    "team": "outsider",
    "ability": "The 1st time a Minion or Demon is nominated & executed by evil, their Townsfolk neighbors are poisoned (even if you’re dead).",
    "jinxes": [
        {
            "id": "riot",
            "reason": "Players who die by nomination register as being executed to the Perfumer."
        }
    ]
}
```

**Comment by zenador** [comment]
+1, this would be a really nice feature :)

**Comment by Skateside** [comment]
Note to self about where to find some homebrew characters (some of them have jinxes)
https://homebrew-script-tool.vercel.app/

**Comment by zenador** [comment]
Hmm this doesn't seem to work. Attached a json with homebrew jinxes from [this tool](https://homebrew-script-tool.vercel.app/), e.g. between the homebrew Vessel and the experimental Lil Monsta, but nothing shows up in the jinxes subsection of the grimoire, not even the standard jinx between Heretic/Spy, and it doesn't show up in the character sheet either (only the standard jinxes like Heretic/Spy).
[json.json](https://github.com/Skateside/pocket-grimoire/files/13582115/json.json)

**Comment by Skateside** [comment]
@zenador I think this is being caused by homebrew characters having jinxes with other homebrew characters. I'll take a look into it, but I think that if homebrew characters have jinxes with other homebrew character, at least one of them is badly written

**Comment by Skateside** [comment]
Hi @zenador 
I've managed to get the inter-homebrew jinxes working.

**Comment by zenador** [comment]
Thank you! The jinxes work great now on the grimoire. But with the [uploaded json](https://github.com/Skateside/pocket-grimoire/files/13582115/json.json) from last time, many of the jinxes are still missing from the character sheet.

**Comment by Skateside** [comment]
Hi @zenador 

I usually forget about the character sheet - sorry about that. The homebrew jinxes should be appearing on the character sheet now.

Due to the way the change needed to be implemented, if you still have a character sheet open on your device and refresh it, you'll notice that the jinxes don't appear to have been fixed. You'll need to re-upload the JSON file to the Pocket Grimoire and get a new character sheet link to see them all.

Cheers
Skateside

**Comment by zenador** [comment]
Works wonderfully now, thank you!

**Comment by b-boechat** [comment]
Hi! I'm commenting here because there's still an issue with inter-homebrew jinxes on the character sheet. The "trick" character's image doesn't show up properly.

Minimal example json:

```
[
    {
        "id": "custom_townsfolk",
        "image": "https://i.imgur.com/qccs0Ct.png",
        "firstNight": 0,
        "firstNightReminder": "",
        "otherNight": 49,
        "otherNightReminder": "",
        "reminders": [],
        "remindersGlobal": [],
        "setup": false,
        "name": "Custom Townsfolk",
        "team": "townsfolk",
        "ability": "Custom Townsfolk ability.",
        "jinxes": [
            {
                "id": "drunk",
                "reason": "Custom Townsfolk -> Drunk"
            }
        ]
    },
    "drunk",
    "baron",
    {
        "id": "custom_demon",
        "image": "https://i.imgur.com/h9TIBbo.png",
        "firstNight": 1,
        "firstNightReminder": "",
        "otherNight": 48,
        "otherNightReminder": "",
        "reminders": [],
        "remindersGlobal": [],
        "setup": false,
        "name": "Custom Demon",
        "team": "demon",
        "ability": "Custom Demon ability.",
        "jinxes": [
            {
                "id": "custom_townsfolk",
                "reason": "Custom Demon -> Custom Townsfolk"
            }
        ]
    }
]
```

There are two jinxes, Custom Townsfolk -> Drunk and Custom Demon -> Custom Townsfolk. Both are correctly displayed on the "jinxes" tab. However, the inter-homebrew jinx doesn't display the Custom Townsfolk's image (a blue square).

![image](https://github.com/user-attachments/assets/7ee433e3-afec-4939-9299-bb4223598a5c)

> I'll take a look into it, but I think that if homebrew characters have jinxes with other homebrew character, at least one of them is badly written

Regarding this, a reasonable use case for inter-homebrew jinxes is a custom script with rethemed official characters.

**Comment by Skateside** [comment]
Hi @b-boechat 

This should be fixed now.

Cheers
Skateside
