### ISSUE TITLE
Homebrew Night Order Badges

### ISSUE THREAD

**Issue by zenador** [Skateside/pocket-grimoire#72]
Bug: When using homebrew characters (e.g. from [this tool](https://homebrew-script-tool.vercel.app/)), they show up properly in the night order section, but the corresponding tokens in the grimoire don't have the red and blue night order badges like the official characters do.

**Comment by Skateside** [comment]
@zenador This should be fixed

**Comment by zenador** [comment]
@Skateside Cool, thank you!
