### ISSUE TITLE
[Question] Where are (French) character translations pulled from?

### ISSUE THREAD

**Issue by papjul** [Skateside/pocket-grimoire#73]
I wanted to fix some mistakes in the French translation, so I had a look at README, which tells us to update this file:
[The Community BotC Translations](https://docs.google.com/spreadsheets/d/1aAJdqSTafHnw01w-WZ94UPx1Me70Kz-EG1NFfBht2tA/edit#gid=923580658)

However, by looking at the most recent commit (118fe6efed94c5c5d635449c2a24805456b4c6a2), I can see a French translation for Ojo character, while the link doesn't have a translation for Ojo yet.

![image](https://github.com/Skateside/pocket-grimoire/assets/1449159/009298c5-b04d-4a31-8a89-7270949aaab6)

![image](https://github.com/Skateside/pocket-grimoire/assets/1449159/15421d98-cf7e-470e-b214-93a9d01e2180)

So, where was that translation pulled from, and how should I proceed with translation updates?

Thanks!

**Comment by Skateside** [comment]
I use the community translations file that you linked to, but I pass the English through Google Translate if the proper translation is missing - which is probably why there are so many mistakes. If you update the community translation file, I'll get your translations into the Pocket Grimoire

**Comment by papjul** [comment]
Thank you for the clarification!

As far as I'm concerned, I still need to get familiar with the game to use proper consistent vocabulary in translations, but I can still fix typos for now. 

The French tab of the Google doc contains a mix of a very good translation (first characters mostly), automatic translation and English, so it's not easy fixing the mess 😅
