### ISSUE TITLE
Alternative versions of the existing translation

### ISSUE THREAD

**Issue by jcx54** [Skateside/pocket-grimoire#77]
Hello. Can I add my version of the translation which already exists in the app? For example, "Svenska" is already exists, can I add "Svenska (by Alex)"? Thank you.

**Comment by Skateside** [comment]
Hi @jcx54 

Although you can, it would be easier if we only had the one version of Svenska. Feel free to update the existing translations - some of them would have come from Google Translate so they might not be completely correct.

Cheers
Skateside
