### ISSUE TITLE
Ability to paste JSON for custom script

### ISSUE THREAD

**Issue by dconman** [Skateside/pocket-grimoire#81]
The custom script tool allows you to copy your script to you clipboard. It would be handy to be able to paste that directly into the application.

**Comment by Skateside** [comment]
🤔 That would be pretty cool.

I like that thought - I'll have a play

**Comment by Skateside** [comment]
Hi @dconman 

I've added that functionality.

Cheers
Skateside

**Comment by dconman** [comment]
Wonderful! Thank you!
