### ISSUE TITLE
Add es-Spain language 

### ISSUE THREAD

**Issue by McDobe** [Skateside/pocket-grimoire#82]
Hi. 

Hello, I have created the required files on the drive to be able to add this language to the game. I would like to see it added to the Pocket Grimoire. Thank you very much for the work you are doing

**Comment by Skateside** [comment]
Hi @McDobe 

Thank you for adding a translation. The Pocket Grimoire now supports Spanish!
https://www.pocketgrimoire.co.uk/es_ES/

Cheers
Skateside
