### ISSUE TITLE
Positioner layout does not work if Grimoire view is hidden when drawing

### ISSUE THREAD

**Issue by pedroadame** [Skateside/pocket-grimoire#84]
When you click "Draw characters" just below selecting a layout, and the grimoire is hidden, the tokens are not drawn in the correct position. They are all piled up in the upper left corner.

**Comment by Skateside** [comment]
Hi @pedroadame 

Would you be able to explain the steps you took to see this bug, and the device you're using, please?

Cheers
Skateside

**Comment by pedroadame** [comment]
Hi @Skateside !

Sure. Just tested both on iOS Safari and Windows Firefox.

1. Clear cache
2. Select edition
3. Make sure "Grimoire" is hidden (i.e view toggled off or collapsed clicking the small arrow)
4. Click "Select characters" - "Highlight Random" - "Add all"

Expected behavior: The Grimoire view is opened and the character tokens are positioned in the selected layout.
Observed behavior: The Grimoire view is opened and all character tokens are piled up on the upper left corner.

Observed workaround:

- Change step 3 in the reproducing steps to "Make sure Grimoire view is shown (i.e toggled on or uncollapsed clicking the small arrow)

**Comment by Skateside** [comment]
Hi @pedroadame 

I've had a play around and I think I've managed to get this bug sorted. Is it still happening for you?

Cheers
Skateside

**Comment by Skateside** [comment]
It's been a month so I'm going to close this issue

**Comment by pedroadame** [comment]
Hi @Skateside Sorry for the delay. Indeed the issue is fixed, thanks!
